name: webgl2_fundamentals_utils
description: Set of utilities for webgl2 based on Gregg Tavares webgl-utils.js for the WebGL2 Fundamentals tutorials.
version: 0.1.0
homepage: https://github.com/ALMaclaine/dart_webgl2_fundamentals_utils

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  effective_dart: ^1.2.1
  test: ^1.14.4
